apiVersion: v1
kind: Service
metadata:
  name: manager-appointment-history
  labels:
    app: manager-appointment-history
spec:
  ports:
    - port: 9000
      targetPort: 9000
  selector:
    app: manager-appointment-history
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: manager-appointment-history-deployment
  labels:
    app: manager-appointment-history-deployment
spec:
  selector:
    matchLabels:
      app: manager-appointment-history
  template:
    metadata:
      labels:
        app: manager-appointment-history
    spec:
      containers:
        - name: manager-appointment-history
          image: nikolai97/doctor-appointment-manager-history:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 9000
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: prod
            - name: MONGO_HOST
              valueFrom:
                configMapKeyRef:
                  name: mongo-config
                  key: host
            - name: MONGO_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: mongo-config
                  key: database
            - name: MONGO_USER
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: database-user
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: database-password
  replicas: 1
